#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#



# Site settings
title: Don's Blog
email: kexiaokai@gmail.com
description: "xiaokai's blog"
baseurl: ""
url: ""

# Build settings
future: false
markdown: kramdown
permalink: /:categories/:title/


# jekyll serve settings 
source: ./_app
destination:  ./_site
port: 4000


# auto: true
