#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#
# Jekyll basic configurations
#

source:       .
destination:  ./_site
timezone:     Asia/Hong_Kong
permalink:    /:title/
markdown:     redcarpet
highlighter:  pygments
paginate: 10
#
# Jekyll serve settings
#

# port:         4321

#
# Jekyll build settings
#

future:       false

#
# Additional Markdown settings
#

redcarpet:
  extensions:
    - footnotes
    - no_intra_emphasis
    - smart
    - space_after_headers
    - superscript
    - tables


# Site settings
title: xeme
email: kexiaokai@gmail.com
description: "xiaokai"
baseurl: ""
url: ""


