#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#

# jekyll serve settings 
source: ./_app
destination: ./_site
permalink: /:categories/:title/


# Site settings
title: Don's Blog
email: kexiaokai@gmail.com
description: "xiaokai's blog"
baseurl: ""
url: ""

# Build settings
future: false
markdown: kramdown




# auto: true
